# Generated by Django 3.2.8 on 2023-01-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_inventory_gerbe_6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='gerbe_1',
            new_name='punto_1',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='gerbe_2',
            new_name='punto_2',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='gerbe_3',
            new_name='punto_3',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='download',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='gerbe_4',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='gerbe_5',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='gerbe_6',
        ),
        migrations.AddField(
            model_name='inventory',
            name='price_6',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
